version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://localhost:27017/tech-challenge
      - NEXTAUTH_SECRET=2a2c1d22b1b66e191057c3700df1d4fe7b8aef0839a1234567890abcdef12345

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
